using Devarc;

public class C2S
{
    public const int RMI_VERSION = 1;

    [NetProtocolAttribute(RMI_ID = 1010)]
    public class Request_Move
	{
		VECTOR3 look;
		DIRECTION move;
	}

    [NetProtocolAttribute(RMI_ID = 1020)]
    public class Request_Chat
	{
		string msg;
		byte[] data;
	}
}

public class S2C
{
    public const int RMI_VERSION = 1;

    [NetProtocolAttribute(RMI_ID = 2010)]
    public class Notify_Player
	{
		HostID id;
		DataPlayer data;
	}

    [NetProtocolAttribute(RMI_ID = 2020)]
    public class Notify_Move
	{
		VECTOR3 look;
		DIRECTION move;
	}

    [NetProtocolAttribute(RMI_ID = 2030)]
    public class Notify_Chat
	{
		string _msg;
	}
}
