using Devarc;

public class C2S
{
    public const int RMI_VERSION = 1;
    public const int RMI_START = 6000;

    public class Request_Move
	{
		VECTOR3 look;
		DIRECTION move;
	}
    public class Request_Chat
	{
		string msg;
	}
}

public class S2C
{
    public const int RMI_VERSION = 1;
    public const int RMI_START = 5000;

    public class Notify_Player
	{
		HostID id;
		DataPlayer data;
	}

    public class Notify_Move
	{
		VECTOR3 look;
		DIRECTION move;
	}

    public class Notify_Chat
	{
		string _msg;
	}
}
