using Devarc;

public class C2S
{
    const int RMI_VERSION = 1;

    [NetProtocolAttribute(RMI_ID = 10010)]
    class Request_Move
	{
		VECTOR3 look;
		DIRECTION move;
	}

    [NetProtocolAttribute(RMI_ID = 10020)]
    class Request_Chat
	{
		string msg;
		byte[] data;
	}
}

public class S2C
{
    const int RMI_VERSION = 1;

    [NetProtocolAttribute(RMI_ID = 11010)]
    class Notify_Player
	{
		HostID id;
		DataPlayer data;
	}

    [NetProtocolAttribute(RMI_ID = 11020)]
    class Notify_Move
	{
		VECTOR3 look;
		DIRECTION move;
	}

    [NetProtocolAttribute(RMI_ID = 11030)]
    class Notify_Chat
	{
		string _msg;
	}
}
