DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE (
	`Name` VARCHAR(256) NOT NULL,
	`ID` VARCHAR(256) NOT NULL PRIMARY KEY,
	`TEXT` VARCHAR(512) NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
