truncate DataCharacter;

insert into DataCharacter (`key`, `data`) VALUES ('HUMAN_FEMALE', '{ \"unit_type\":\"HUMAN_FEMALE\", \"name\":\"인간(여)\", \"items\":[\"ELF_MALE\",\"ELF_FEMALE\"], \"stats\":[{\"str\":\"11\"}], \"ability\":{}, \"nodes\":[\"1\",\"2\",\"'';\\\"3\"], \"unit_uid\":\"1\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('HUMAN_MALE', '{ \"unit_type\":\"HUMAN_MALE\", \"name\":\"인간(남)\", \"items\":[], \"stats\":[{\"str\":\"12\"}], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"2\", \"specialCode\":\"\\\"\\\\;,./<>\" }');
insert into DataCharacter (`key`, `data`) VALUES ('ELF_FEMALE', '{ \"unit_type\":\"ELF_FEMALE\", \"name\":\"엘프(여)\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"3\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('ELF_MALE', '{ \"unit_type\":\"ELF_MALE\", \"name\":\"엘프(남)\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"4\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DARKELF_FEMALE', '{ \"unit_type\":\"DARKELF_FEMALE\", \"name\":\"다크엘프(여)\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"5\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DARKELF_MALE', '{ \"unit_type\":\"DARKELF_MALE\", \"name\":\"다크엘프(남)\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"6\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DWARF_FEMALE', '{ \"unit_type\":\"DWARF_FEMALE\", \"name\":\"드와프(여)\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"7\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DWARF_MALE', '{ \"unit_type\":\"DWARF_MALE\", \"name\":\"드와프(남)\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"8\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('GOBLIN', '{ \"unit_type\":\"GOBLIN\", \"name\":\"고블린\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"9\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('IMP', '{ \"unit_type\":\"IMP\", \"name\":\"임프\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"10\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('MUMMY', '{ \"unit_type\":\"MUMMY\", \"name\":\"미라\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"11\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('ORC', '{ \"unit_type\":\"ORC\", \"name\":\"오크\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"12\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('TROLL', '{ \"unit_type\":\"TROLL\", \"name\":\"트롤\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"13\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('UNDEAD', '{ \"unit_type\":\"UNDEAD\", \"name\":\"언데드\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"14\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DRAGON_BLACK', '{ \"unit_type\":\"DRAGON_BLACK\", \"name\":\"블랙 드래곤\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DRAGON_RED', '{ \"unit_type\":\"DRAGON_RED\", \"name\":\"레드 드래곤\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"\", \"specialCode\":\"\" }');
insert into DataCharacter (`key`, `data`) VALUES ('DRAGON_UNDEAD', '{ \"unit_type\":\"DRAGON_UNDEAD\", \"name\":\"본 드래곤\", \"items\":[], \"stats\":[], \"ability\":{}, \"nodes\":[], \"unit_uid\":\"\", \"specialCode\":\"\" }');
