DROP TABLE IF EXISTS MESSAGE;
CREATE TABLE MESSAGE (
	`Name` varchar(50) NOT NULL,
	`ID` varchar(50) NOT NULL PRIMARY KEY,
	`TEXT` varchar(50) NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
